name: dea
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0
  - affine=2.4.0
  - aiobotocore=2.25.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.0
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - alembic=1.17.0
  - antimeridian=0.4.3
  - anyio=4.11.0
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asciitree=0.3.3
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - boltons=25.0.0
  - boto3=1.40.49
  - botocore=1.40.49
  - bottleneck=1.6.0
  - branca=0.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.21.3
  - c-compiler=1.11.0
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.1
  - cairo=1.18.4
  - capnproto=1.2.0
  - cattrs=25.3.0
  - cctools=1024.3
  - cctools_osx-arm64=1024.3
  - certifi=2025.10.5
  - cffi=2.0.0
  - cfitsio=4.6.3
  - cftime=1.6.4
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - ciso8601=2.3.3
  - clang=19.1.7
  - clang-19=19.1.7
  - clang_impl_osx-arm64=19.1.7
  - clang_osx-arm64=19.1.7
  - clangxx=19.1.7
  - clangxx_impl_osx-arm64=19.1.7
  - clangxx_osx-arm64=19.1.7
  - click=8.3.0
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - compiler-rt=19.1.7
  - compiler-rt_osx-arm64=19.1.7
  - compilers=1.11.0
  - contourpy=1.3.3
  - cpython=3.12.12
  - cryptography=46.0.3
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2025.10.0
  - dask-core=2025.10.0
  - dask-image=2024.5.3
  - datacube=1.9.10
  - datadog=0.52.1
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecat=2.1.3
  - deprecated=1.2.18
  - distributed=2025.10.0
  - docopt-ng=0.9.0
  - eodatasets3=1.9.3
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fasteners=0.19
  - fiona=1.10.1
  - flox=0.10.7
  - fmt=12.0.0
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fortran-compiler=1.11.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - gcsfs=2025.9.0
  - gdal=3.10.3
  - geoalchemy2=0.18.0
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.14.0
  - geotiff=1.7.4
  - gflags=2.2.2
  - gfortran=14.3.0
  - gfortran_impl_osx-arm64=14.3.0
  - gfortran_osx-arm64=14.3.0
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - google-api-core=2.25.2
  - google-auth=2.41.1
  - google-auth-oauthlib=1.2.2
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.4.1
  - google-crc32c=1.7.1
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.70.0
  - greenlet=3.2.4
  - grpcio=1.73.1
  - h11=0.16.0
  - h2=4.3.0
  - h5netcdf=1.7.3
  - h5py=3.15.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagecodecs=2025.8.2
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - isl=0.26
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - json-c=0.18
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jxrlib=1.1
  - kealib=1.6.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lazy-loader=0.4
  - lcms2=2.17
  - ld64=955.13
  - ld64_osx-arm64=955.13
  - legacy-cgi=2.6.3
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.2
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libcrc32c=1.1.2
  - libcurl=8.16.0
  - libcxx=21.1.4
  - libcxx-devel=19.1.7
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal=3.10.3
  - libgdal-arrow-parquet=3.10.3
  - libgdal-core=3.10.3
  - libgdal-fits=3.10.3
  - libgdal-grib=3.10.3
  - libgdal-hdf4=3.10.3
  - libgdal-hdf5=3.10.3
  - libgdal-jp2openjpeg=3.10.3
  - libgdal-kea=3.10.3
  - libgdal-netcdf=3.10.3
  - libgdal-pdf=3.10.3
  - libgdal-pg=3.10.3
  - libgdal-postgisraster=3.10.3
  - libgdal-tiledb=3.10.3
  - libgdal-xls=3.10.3
  - libgfortran=15.2.0
  - libgfortran-devel_osx-arm64=14.3.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libpq=18.0
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=21.1.4
  - llvm-tools=19.1.7
  - llvm-tools-19=19.1.7
  - llvmlite=0.45.1
  - locket=1.0.0
  - lxml=6.0.2
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mako=1.3.10
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - minizip=4.0.10
  - mistune=3.1.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - munkres=1.1.4
  - narwhals=2.9.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.3
  - networkx=3.5
  - nlohmann_json=3.12.0
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.117
  - numba=0.62.1
  - numbagg=0.9.3
  - numcodecs=0.15.1
  - numexpr=2.14.1
  - numpy=1.26.4
  - numpy_groupies=0.11.3
  - oauthlib=3.3.1
  - odc-algo=0.2.3
  - odc-apps-dc-tools=1.9.4
  - odc-cloud=0.2.5
  - odc-dscache=0.2.3
  - odc-geo=0.5.0rc1
  - odc-io=0.2.2
  - odc-loader=0.5.1
  - odc-stac=0.4.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openpyxl=3.1.5
  - openssl=3.5.4
  - opt_einsum=3.4.0
  - orc=2.2.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pims=0.7
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pooch=1.8.2
  - poppler=25.07.0
  - poppler-data=0.4.12
  - postgresql=18.0
  - proj=9.7.0
  - prometheus-cpp=1.3.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=6.31.1
  - psutil=7.1.1
  - psycopg2=2.9.10
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydap=3.5.8
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyobjc-core=12.0
  - pyobjc-framework-cocoa=12.0
  - pyogrio=0.11.0
  - pyopenssl=25.3.0
  - pyparsing=3.2.5
  - pyproj=3.7.2
  - pysocks=1.7.1
  - pystac=1.14.1
  - pystac-client=0.9.0
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-lmdb=1.7.5
  - python-rapidjson=1.22
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyu2f=0.1.5
  - pywavelets=1.9.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rasterio=1.4.3
  - rav1e=0.7.1
  - re2=2025.08.12
  - readline=8.2
  - referencing=0.37.0
  - requests=2.32.5
  - requests-cache=1.2.1
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rio-stac=0.12.0
  - rioxarray=0.19.0
  - rpds-py=0.27.1
  - rsa=4.9.1
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - s3fs=2025.9.0
  - s3transfer=0.14.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.1.2
  - sigtool=0.1.3
  - six=1.17.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - spdlog=1.16.0
  - sqlalchemy=2.0.44
  - sqlite=3.50.4
  - stack_data=0.6.3
  - structlog=25.4.0
  - svt-av1=3.1.2
  - tapi=1300.6.5
  - tblib=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2025.10.16
  - tiledb=2.29.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.3.0
  - toolz=1.1.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzcode=2025b
  - tzdata=2025b
  - ujson=5.11.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - url-normalize=2.2.1
  - urllib3=2.5.0
  - urlpath=1.2.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - webob=1.8.9
  - websocket-client=1.9.0
  - wheel=0.45.1
  - wrapt=1.17.3
  - xarray=2025.10.1
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zarr=2.18.7
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
    - deafrica-tools==2.5.11


